#!/bin/bash

source ./resources/scripts/infra_testes.sh

echo OK $CONTADOR_EXERCICIOS
echo OK $EXERCICIOS_CORRETOS

TIPO_VALIDACAO=$1
EXERCICIO=$2

$1 $2;

echo 2 $EXERCICIOS_CORRETOS CORRETOS DE $CONTADOR_EXERCICIOS EXERCICIOS.

if [ $EXERCICIOS_CORRETOS -eq $CONTADOR_EXERCICIOS ]; then
	return 0;
else
	return 1;
fi