#!/bin/bash

source ./resources/scripts/infra_testes.sh

echo OK $CONTADOR_EXERCICIOS
echo OK $EXERCICIOS_CORRETOS
echo OK $RESULTADO_TESTES

TIPO_VALIDACAO=$1
EXERCICIO=$2

$1 $2;

echo RESULTADO_TESTES $RESULTADO_TESTES
echo 2 $EXERCICIOS_CORRETOS CORRETOS DE $CONTADOR_EXERCICIOS EXERCICIOS.

if [ "$RESULTADO_TESTES" -eq 2 ]; then
	return $RESULTADO_TESTES;
fi

if [ "$EXERCICIOS_CORRETOS" -eq "$CONTADOR_EXERCICIOS" ]; then
	RESULTADO_TESTES=0
	return $RESULTADO_TESTES
else
	RESULTADO_TESTES=1
	return $RESULTADO_TESTES
fi